def complementoRNA(dna):
    rna = ''
    for base_nitrogenada in dna:
        if base_nitrogenada == 'A':
            rna+='U'
        elif base_nitrogenada=='T':
            rna+='A'
        elif base_nitrogenada=='C':
            rna+='G'
        elif base_nitrogenada=='G':
            rna+='C'
        else:
            rna+=base_nitrogenada
    return rna

def complemento(dna):
    dnacomplemento = ''
    for base_nitrogenada in dna:
        if base_nitrogenada == 'A':
            dnacomplemento+='T'
        elif base_nitrogenada=='T':
            dnacomplemento+='A'
        elif base_nitrogenada=='C':
            dnacomplemento+='G'
        elif base_nitrogenada=='G':
            dnacomplemento+='C'
        else:
            rna+=base_nitrogenada
    return dnacomplemento

def transcricao(dna):
    return complementoRNA(complemento(dna))

if  __name__ == '__main__':
    entrada = 'CCAAATATATGATCTATATTCAGGTGAAACGGGCCTCATCGGGTATCCCGGTGCACGAGACAGAAGGGAGCAATACACTCGGGAGATCTGGTCTTTACTTGGCAAAGTTATGCGAAAGACAAAGCCTAACTTAAACCTCGTGTCGTTTGGCTACAAGTAGCCACGTGATTCAATGTCTCTATTAGCAATACATAGGTTGTAGATTTGTAGTGTATACTTGTACGCAGCAAGTCGGTAAAGCGCATAAGGCCGTATCCCTAGTAGCTTGCTGTTAAGCATGGTTACGTGTCACTAACCGCCGGCTACTCCTTAGTCAGAGTTCTGGTAGTCCGTGTCACATAGATTAGGGAAAAGTACACCATCGCAAATGAGTGCTGGCGAGCTCGCGTATTGTATGCAGGTCCCGCCGTGGAAGCGGCAAGCATCCTCGCAGGCCGCAGCATACGTGGTTCCCTGGGTGTCTTTCTCGCAGCGATGGGGCTTCACGACAGCGCTGATCCAAACCTTCTCCGGTGCCCCCGAACTTTCATGTGTTTTCTCCCTTAGTGGATAATATCTGAGTTCTATGCTTGGGTATGTTTCTCGCATACTCTGACACAGTGACTACTGAGGTCCCTCAAATTCATCGGCCGCAGACACGGTGGACAAGGCATCAGTCTTCAGATAAGAAATGAGGCCACCCTATTATCTCAGTTTAGCCTGCTCCACGGTCTATTAACTGAGTCGTCATTTGGGGGGTAGCGTGGTAAATAAGCCGATCGTATGTCCTCGATGTGATCTTCGCGTATGGGTGAACGAATACGTAGACCTCACCATGGGTGGTCTGACCTTCTCACCTCCCTCCGGCGATGAAAAAGGCTCCGAAGGTCCCTGATTGTCTCGGACGCTCGGTACGTTTCTTCGGCACTAAACCAACTAGTGTACTTAGTTGAGTCTCATGGACTCTGTTTGTAGCCGGGCCGAGCCCACCCCCGGCACGTGGGGCGCTGGGCTCTTGACGCTCGATGGGATGCATCTATTGATGAATAGGCCCGATGCTCCAGACGGAGCTTTATTATGTTTGCTTGAACGAAGGAGTCCACAGAGGGCCGCACAGTTCGTGACAGCAGTTCCTCAGCTCGCTGGCGCGAGTATGCGGCTTTTTTGTCCGAATAACATCGACTTAAAAGGGCGTCGGTTCGACCCCACTACAGAACCTACCAGACCGTTCCGGACGCGCCGCTTATTAGGCTCATTTTGAGATTTGGATGACCGGTTACCGTTTCTAGCGTATCCCGACTCGCTTCTATAGTACCCGTCTCCGCATCTGTCTTTTGACAGTCCAGTATCGTCGTGAGACCATACCGGACAGGGCACGCATAGCTACTAGAGCAGCGTTATGCTTACGCGCATAGACGATCTATACATGCCTCTAAACCACGCCACGGCATGAAATGTAAACATCGCTTTTTTGGACGAGCTCTGCAGGGACTGCGGTTTGATTGCAGAGGGGACCATACC'
    arquivo = open('rna-mensageiro-output.txt','w')
    saida = transcricao(entrada)
    arquivo.write(saida+'\n')
    arquivo.close()
    print("Saída salva, no diretório corrente!")
    
